Repository BigData23th/Python, pull requests merged in 2023-02, with the labels that each got.

#1 자기소개
  submission/Myun9hyun/readme.md
Labels: 개인과제

#2 자기소개
  submission/whataLin/readme.md
Labels: 개인과제

#4 자기소개
  submission/Yeaaaaaaah/readme.md
Labels: 개인과제

#5 자기소개
  submission/JaejinLee1215/readme.md
Labels: 개인과제

#6 자기소개
  submission/qus0in/readme.md
Labels: 개인과제

#7 자기소개
  submission/Heecong/readme.md
Labels: 개인과제

#8 자기소개
  submission/zihvvan/README.md
Labels: 개인과제

#9 자기소개
  submission/andy9806/readme.md
Labels: 개인과제

#58 점심
  submission/suhdongjoon/01_first_webapp/app.py
  submission/suhdongjoon/01_first_webapp/requirements.txt
  submission/suhdongjoon/MyFirstNotebook.ipynb
  submission/suhdongjoon/ch01_01_기본_문법과_숫자_계산sdj.ipynb
  submission/suhdongjoon/ch01_02_변수+입력+출력_sdj.ipynb
  submission/suhdongjoon/readme.md
Labels: 개인과제, KPT

#60 2022.2.28.(화) 점심식사_주현성
  submission/JuHS/01_first_webapp/app.py
  submission/JuHS/01_first_webapp/requirements.txt
Labels: 개인과제, STAR

#69 점심식사 과제
  Ch01_03_마크다운.ipynb
  Ch_01_복습.ipynb
  material/01_first_webapp/app.py
  submission/Kimdongha96/01_first_webapp/app.py
  submission/Kimdongha96/01_first_webapp/requirements.txt
  submission/Kimdongha96/ch01_02_변수+입력+출력_ipynb의_사본.ipynb
  과제2_점심식사 STAR기법.ipynb
Labels: 개인과제, STAR

#63 과제2 점심식사
  submission/JaejinLee1215/01_first_webapp/app.py
  submission/JaejinLee1215/01_first_webapp/requirements.txt
  submission/JaejinLee1215/MyFirstNotebook.ipynb
  submission/JaejinLee1215/ch01_01_기본_문법과_숫자_계산_공유용_ipynb의_사본.ipynb
  submission/JaejinLee1215/ch01_02_변수+입력+출력_공유용_ipynb의_사본.ipynb
  submission/JaejinLee1215/ch01_03_마크다운.ipynb
  submission/JaejinLee1215/ch01_복습_코드.ipynb
  submission/JaejinLee1215/과제2.ipynb
Labels: 개인과제, STAR

#66 02-28 오늘 점심
  material/01_first_webapp/app.py
  my_first_notebook_0227.ipynb
  submission/woohyukjang/01_first_webapp/app.py
  submission/woohyukjang/01_first_webapp/requirements.txt
  submission/woohyukjang/ch01_02_변수+입력+출력_공유용.ipynb
Labels: 개인과제, STAR

#52 2023_02_28_점심_STAR
  submission/cc5547/01_first_webapp/app.py
  submission/cc5547/01_first_webapp/requirements.txt
  submission/cc5547/cc5547
  submission/cc5547/ch01_02_변수+입력+출력_공유용.ipynb
  submission/cc5547/ch01_03_마크다운.ipynb
  submission/cc5547/ch01_복습_230228.ipynb
  submission/cc5547/raedme.md
  submisson/cc5547/230227_ch01_02_변수+입력+출력_공유용_cc5547_ipynb의_사본.ipynb
Labels: 개인과제, STAR

#65 점심과제
  submission/JoySoon/01_first_webapp/app.py
  submission/JoySoon/01_first_webapp/requirements.txt
  submission/JoySoon/ch01_01_기본_문법과_숫자_계산_KSW_ipynb의_사본.ipynb
  submission/JoySoon/ch01_02_변수+입력+출력_KSW.ipynb
  submission/JoySoon/ch01_03_마크다운.ipynb
  submission/JoySoon/ch01_복습.ipynb
Labels: 개인과제, STAR

#72 0228 점심시간 과제
  submission/CHOISEONGGU/0228_점심.ipynb
Labels: 개인과제, 4줄일기

#76 23.02.28 필기
  submission/qus0in/ch02_01_불과+비교+논리+연산자_qus0in.ipynb
  submission/qus0in/ch02_02_문자열_qus0in.ipynb
Labels: 필기, KPT, STAR, 4줄일기

#77 Ch02 Review
  submission/mastgm0817/01_first_webapp/app.py
  submission/mastgm0817/01_first_webapp/requirements.txt
  submission/mastgm0817/lecture/Ch01/ch01_01_기본_문법과_숫자_계산.ipynb
  submission/mastgm0817/lecture/Ch01/ch01_02_변수+입력+출력.ipynb
  submission/mastgm0817/lecture/Ch01/ch01_03_MarkDown.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_01_불과+비교+논리+연산자.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_02_문자열.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_03_리스트와_튜플.ipynb
  submission/mastgm0817/lecture/SelfStudy/map_lambda.ipynb
  submission/mastgm0817/lecture/SelfStudy/numpy_연습.ipynb
Labels: 필기, 4줄일기

#78 0228
  submission/andy9806/0228.ipynb
Labels: 필기, STAR

#79 23.02.28 2일차 수업 피드백
  submission/Yeaaaaaaah/MyFirstNoteBook.ipynb
  submission/Yeaaaaaaah/app.py
  submission/Yeaaaaaaah/ch01_01_기본_문법과_숫자_계산.ipynb
  submission/Yeaaaaaaah/ch01_02_변수_입력_출력.ipynb
  submission/Yeaaaaaaah/ch01_03_마크다운.ipynb
  submission/Yeaaaaaaah/ch02_01_불과+비교+논리+연산자_Yeaaaaaaah.ipynb
  submission/Yeaaaaaaah/ch02_02_문자열.ipynb
  submission/Yeaaaaaaah/ch02_03_리스트와_튜플.ipynb
Labels: 필기, 4줄일기

#80 23.02.28
  submission/zihvvan/ch01_03_마크다운.ipynb
  submission/zihvvan/ch01_복습_ipynb의_사본.ipynb
  submission/zihvvan/ch02_01_불과+비교+논리+연산자_ipynb의_사본.ipynb
  submission/zihvvan/ch02_02_문자열_ipynb의_사본.ipynb
  submission/zihvvan/ch02_03_리스트와_튜플_ipynb의_사본.ipynb
Labels: 필기, KPT

#89 2일차 수업 회고
  submission/Myun9hyun/app.py
  submission/Myun9hyun/ch01_01_기본_문법과_숫자_계산_Myun9hyun_ipynb의_사본.ipynb
  submission/Myun9hyun/ch01_02_변수+입력+출력_Myun9hyun.ipynb
  submission/Myun9hyun/ch01_03_Day01_3_마크다운.ipynb
  submission/Myun9hyun/ch01_복습.ipynb
  submission/Myun9hyun/ch02_01_불과+비교+논리+연산자_공유용.ipynb
  submission/Myun9hyun/ch02_02_문자열_공유용.ipynb
  submission/Myun9hyun/ch02_03_리스트와_튜플_공유용.ipynb
Labels: 필기, STAR

#84 23.02.28 필기
  submission/JaejinLee1215/ch02_01_불과+비교+논리+연산자_이재진.ipynb
  submission/JaejinLee1215/ch02_02_문자열_이재진.ipynb
  submission/JaejinLee1215/ch02_03_리스트와_튜플_이재진.ipynb
Labels: 필기, STAR

#85 2/28일 수업 필기
  submission/JoySoon/ch02_01_불과+비교+논리+연산자_KSW.ipynb
  submission/JoySoon/ch02_02_문자열_KSW.ipynb
  submission/JoySoon/ch02_03_리스트와_튜플_KSWipynb.ipynb
  submission/qus0in/ch02_02_문자열_KSW.ipynb
Labels: 필기, 4줄일기

#90 23.02.28 수업 회고
  submission/Heecong/ch02_01_불과+비교+논리+연산자.ipynb
  submission/Heecong/ch02_02_문자열.ipynb
  submission/Heecong/ch02_03_리스트와_튜플.ipynb
Labels: 필기, STAR

#97 2/28 수업필기
  submission/KHB2937/ch02_01_불과+비교+논리+연산자_희범_ipynb의_사본.ipynb
  submission/KHB2937/ch02_02_문자열_희범_ipynb의_사본.ipynb
  submission/KHB2937/ch02_03_리스트와_튜플_희범_ipynb의_사본.ipynb
Labels: 필기, STAR

#92 필기 2023.02.28
  submission/hiid0726/ch02_01_불과+비교+논리+연산자_ym.ipynb
  submission/hiid0726/ch02_02_문자열_ym.ipynb
  submission/hiid0726/ch02_03_리스트와_튜플_ym.ipynb
Labels: 필기, STAR

#94 23.02.28
  Ch01_03_마크다운.ipynb
  Ch_01_복습.ipynb
  submission/Kimdongha96/.ipynb
  submission/Kimdongha96/01_first_webapp.ipynb
  submission/Kimdongha96/ch02_01_불과+비교+논리+연산자.ipynb
  submission/Kimdongha96/ch02_02_문자열.ipynb
  submission/Kimdongha96/ch02_03_리스트와_튜플.ipynb
Labels: 필기, 4줄일기

#96 230228 필기내용, 회고
  submission/tkd8973/ch02_01_불과+비교+논리+연산자_qus0in_ipynb의_사본.ipynb
  submission/tkd8973/ch02_02_문자열.ipynb
  submission/tkd8973/ch02_03_리스트와_튜플.ipynb
Labels: 필기, KPT

#98 회고
  submission/suhdongjoon/ch02_01_불과+비교+논리+연산자_sdj.ipynb
  submission/suhdongjoon/ch02_02_문자열_sdj.ipynb
  submission/suhdongjoon/ch02_03_리스트와_튜플_sdj.ipynb
Labels: 필기, KPT

#99 0228 회고
  submission/cc5547/230228_ch02_01_불과+비교+논리+연산자_최용재.ipynb
  submission/cc5547/230228_ch02_02_문자열_최용재.ipynb
  submission/cc5547/230228_ch02_03_리스트와_튜플_최용재.ipynb
Labels: 필기, STAR
