Repository BigData23th/Python, pull requests merged in 2023-03, with the labels that each got.

#103 0302
  submission/andy9806/0302.ipynb
Labels: 필기, STAR

#104 3월 2일(목) 3일차 회고
  submission/Yeaaaaaaah/ch02_04_시퀀스_자료형.ipynb
  submission/Yeaaaaaaah/ch02_05_딕셔너리.ipynb
  submission/Yeaaaaaaah/ch02_06_조건문.ipynb
  submission/Yeaaaaaaah/ch02_07_반복문.ipynb
Labels: 필기, 4줄일기

#105 2023. 3. 2.(목) 회고_주현성
  submission/JuHS/ch02_04_시퀀스_자료형(공유용).ipynb
  submission/JuHS/ch02_05_딕셔너리(공유용).ipynb
  submission/JuHS/ch02_06_조건문(공유용).ipynb
  submission/JuHS/ch02_07_반복문(공유용).ipynb
Labels: 필기, STAR

#106 Day 03 회고
  submission/Myun9hyun/ch02_01_복습.ipynb
  submission/Myun9hyun/ch02_04_시퀀스_자료형_공유용.ipynb
  submission/Myun9hyun/ch02_05_딕셔너리_공유용.ipynb
  submission/Myun9hyun/ch02_06_조건문_공유용.ipynb
  submission/Myun9hyun/ch02_07_반복문_공유용.ipynb
  submisson/Myun9hyun/ch02_01_복습.ipynb
Labels: 필기, 4줄일기

#107 회고
  submission/jinu/ch02_01_복습.ipynb
  submission/jinu/ch02_01_불과+비교+논리+연산자_qus0in.ipynb
Labels: 필기, STAR

#121 Day3 회고 (시퀀스 자료형, 딕셔너리, 조건문)
  submission/mastgm0817/lecture/Ch02/ch02_04_시퀀스_자료형.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_05_딕셔너리.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_06_조건문.ipynb
  submission/mastgm0817/lecture/SelfStudy/pandas_practice.ipynb
Labels: 필기, 4줄일기

#120 2023.03.02 회고
  submission/suhdongjoon/ch02_04_시퀀스_자료형_sdj.ipynb
  submission/suhdongjoon/ch02_05_딕셔너리_sdj.ipynb
  submission/suhdongjoon/ch02_06_조건문_sdj.ipynb
  submission/suhdongjoon/ch02_07_반복문_sdj.ipynb
Labels: 필기, 4줄일기

#119 23.03.02 수업내용
  submission/CHOISEONGGU/Ch02_02_복습.ipynb
  submission/CHOISEONGGU/Ch02_1_자료구조와_흐름제어_복습.ipynb
  submission/CHOISEONGGU/ch02_04_시퀀스_자료형_ChoiSG.ipynb
  submission/CHOISEONGGU/ch02_05_딕셔너리_ChoiSG.ipynb
  submission/CHOISEONGGU/ch02_06_조건문_ChoiSG.ipynb
  submission/CHOISEONGGU/ch02_07_리스트_응용_ChoiSG.ipynb
  submission/CHOISEONGGU/ch02_07_반복문_ChoiSG.ipynb
  submission/CHOISEONGGU/ch02_08_문자열_응용_ChoiSG.ipynb
Labels: 필기, 4줄일기

#128 회고
  submission/jinu/ch02_01_복습.ipynb
  submission/jinu/ch02_01_불과+비교+논리+연산자_qus0in.ipynb
Labels: 필기, STAR

#117 23.03.02. 수업 회고
  submission/JaejinLee1215/ch02_01_복습.ipynb
  submission/JaejinLee1215/ch02_02_복습.ipynb
  submission/JaejinLee1215/ch02_04_시퀀스_자료형_이재진.ipynb
  submission/JaejinLee1215/ch02_05_딕셔너리_이재진.ipynb
  submission/JaejinLee1215/ch02_06_조건문_이재진.ipynb
  submission/JaejinLee1215/ch02_07_리스트_응용_이재진.ipynb
  submission/JaejinLee1215/ch02_07_반복문_이재진.ipynb
  submission/JaejinLee1215/ch02_08_문자열_응용_이재진.ipynb
Labels: 필기, STAR

#116 2023_03_02_최용재
  submission/cc5547/03_01_식사조_랜덤뽑기.ipynb
  submission/cc5547/2023_03_02_ch02_01_복습.ipynb
  submission/cc5547/2023_03_02_ch02_04_시퀀스_자료형.ipynb
  submission/cc5547/2023_03_02_ch02_05_딕셔너리_공유용.ipynb
  submission/cc5547/2023_03_02_ch02_06_조건문_공유용.ipynb
  submission/cc5547/2023_03_02_ch02_06_조건문_최용.ipynb
  submission/cc5547/2023_03_02_ch02_07_반복문_.ipynb
  submission/cc5547/2023_03_03_ch02_02_복습.ipynb
Labels: 필기, 4줄일기

#115 2023.03.03(회고)
  submission/1주차/ch02_04_시퀀스_자료형_ym.ipynb
  submission/hiid0726/ch02_04_시퀀스_자료형_ym.ipynb
  submission/hiid0726/ch02_05_딕셔너리.ipynb
  submission/hiid0726/ch02_05_딕셔너리_확인.ipynb
  submission/hiid0726/ch02_06_조건문_ym.ipynb
  submission/hiid0726/ch02_07_리스트_응용_ym.ipynb
  submission/hiid0726/ch02_08_문자열_응용_ym.ipynb
  submission/hiid0726/ch02_1_복습.ipynb
  submission/hiid0726/ch02_2_복습.ipynb
Labels: 필기, STAR

#113 day3 회고
  submission/jyeongvv/ch02_02_복습.ipynb
  submission/jyeongvv/ch02_04_시퀀스_자료형.ipynb
  submission/jyeongvv/ch02_05_딕셔너리.ipynb
  submission/jyeongvv/ch02_06_조건문.ipynb
  submission/jyeongvv/ch02_07_리스트_응용.ipynb
  submission/jyeongvv/ch02_07_반복문.ipynb
  submission/jyeongvv/ch02_08_문자열_응용.ipynb
  submission/jyeongvv/ch02_1_복습.ipynb
Labels: 필기, 4줄일기

#112 3일차 회고
  submission/jaiwon880/ch02_02_복습.ipynb
  submission/jaiwon880/ch02_05_딕셔너리.ipynb
  submission/jaiwon880/ch02_06_조건문.ipynb
  submission/jaiwon880/ch02_07_리스트_응용.ipynb
  submission/jaiwon880/ch02_07_반복문.ipynb
  submission/jaiwon880/ch02_08_문자열_응용.ipynb
Labels: 필기, STAR

#129 2023.03.03
  submission/zihvvan/ch02_01_복습.ipynb
  submission/zihvvan/ch02_02_복습.ipynb
  submission/zihvvan/ch02_04_시퀀스_자료형_ipynb의_사본.ipynb
  submission/zihvvan/ch02_05_딕셔너리_ipynb의_사본.ipynb
  submission/zihvvan/ch02_06_조건문_ipynb의_사본.ipynb
  submission/zihvvan/ch02_07_반복문_ipynb의_사본.ipynb
  submission/zihvvan/ch02_08_문자열_응용_part1_zihvvan.ipynb
Labels: 필기, 4줄일기

#130 4일차 회고
  submission/jaiwon880/ch02_02_복습1.ipynb
  submission/jaiwon880/ch02_03_복습.ipynb
  submission/jaiwon880/ch02_09_문자열_서식.ipynb
  submission/jaiwon880/ch02_10_딕셔너리_응용.ipynb
  submission/jaiwon880/ch03_01_함수.ipynb
Labels: 필기, STAR

#132 2023.03.03 회고
  submission/suhdongjoon/ch02_08_리스트_응용_sdj.ipynb
  submission/suhdongjoon/ch02_09_문자열_응용_sdj.ipynb
Labels: 필기, KPT

#134 23.03.03 수업 회고
  submission/JaejinLee1215/ch01_01_기본_문법과_숫자_계산_이재진.ipynb
  submission/JaejinLee1215/ch01_02_변수+입력+출력_이재진.ipynb
  submission/JaejinLee1215/ch01_03_마크다운.ipynb
  submission/JaejinLee1215/ch01_복습_코드.ipynb
  submission/JaejinLee1215/ch02_01_불과+비교+논리+연산자_이재진.ipynb
  submission/JaejinLee1215/ch02_02_문자열_이재진.ipynb
  submission/JaejinLee1215/ch02_03_리스트와_튜플_이재진.ipynb
  submission/JaejinLee1215/ch02_09_문자열_서식_이재진.ipynb
  submission/JaejinLee1215/ch02_10_딕셔너리_응용_이재진.ipynb
Labels: 필기, STAR

#135 23_03_03_회고
  submission/cc5547/2023_02_27_ch01_01_기본문법_숫자_계산.ipynb
  submission/cc5547/2023_02_27_ch01_02_변수+입력+출력_공유용.ipynb
  submission/cc5547/2023_02_27_ch01_03_마크다운.ipynb
  submission/cc5547/2023_02_27_raedme.md
  submission/cc5547/2023_02_28_ch01_복습.ipynb
  submission/cc5547/2023_02_28_ch02_01_불과+비교+논리+연산자_최용재.ipynb
  submission/cc5547/2023_02_28_ch02_02_문자열_최용재.ipynb
  submission/cc5547/2023_02_28_ch02_03_리스트와_튜플_최용재.ipynb
  submission/cc5547/2023_03_01_식사조_랜덤뽑기.ipynb
  submission/cc5547/2023_03_02_ch02_06_조건문_공유용.ipynb
  submission/cc5547/2023_03_03_ch02_02_복습.ipynb
  submission/cc5547/2023_03_03_ch02_07_리스트_응용.ipynb
  submission/cc5547/2023_03_03_ch02_08_문자열.ipynb
  submission/cc5547/2023_03_06_ch02_03_복습.ipynb
  submission/cc5547/2023_03_06_ch02_09_문자열_서식.ipynb
  submission/cc5547/2023_03_06_ch02_10_딕셔너리_응용.ipynb
  submission/cc5547/2023_03_06_ch03_01_함수.ipynb
  submisson/cc5547/2023_02_27_ch01_01_기본문법_숫자_계산.ipynb
Labels: 필기, STAR

#137 230306_회고
  submission/tkd8973/리스트_복습_.ipynb
Labels: 필기, STAR

#139 3월 6일 5일차 피드백
  submission/Yeaaaaaaah/ch02_03_복습.ipynb
  submission/Yeaaaaaaah/ch02_07_리스트_응용.ipynb
  submission/Yeaaaaaaah/ch02_08_문자열_응용.ipynb
  submission/Yeaaaaaaah/ch02_09_문자열_서식.ipynb
  submission/Yeaaaaaaah/ch02_10_딕셔너리_응용.ipynb
  submission/Yeaaaaaaah/ch03_01_함수.ipynb
Labels: 필기, 4줄일기

#140 0306
  submission/andy9806/0306.ipynb
Labels: 필기, STAR

#142 3/6 회고
  submission/whataLin/app.py
  submission/whataLin/ch02/ch02_09_문자열_서식.ipynb
  submission/whataLin/ch02/ch02_10_딕셔너리_응용.ipynb
  submission/whataLin/ch02/ch02정리2.ipynb
  submission/whataLin/ch03/ch03_01_함수.ipynb
Labels: 필기, 4줄일기

#143 03-06회고
  submission/KHB2937/ch02_01_복습.ipynb
  submission/KHB2937/ch02_02_복습_ipynb의_사본.ipynb
  submission/KHB2937/ch02_03_복습_ipynb의_사본.ipynb
  submission/KHB2937/ch02_04_시퀀스_자료형_희범_ipynb의_사본.ipynb
  submission/KHB2937/ch02_05_딕셔너리_희범_ipynb의_사본.ipynb
  submission/KHB2937/ch02_06_조건문_희범_ipynb의_사본.ipynb
  submission/KHB2937/ch02_07_리스트_응용_희범_ipynb의_사본.ipynb
  submission/KHB2937/ch02_07_반복문_희범_ipynb의_사본.ipynb
  submission/KHB2937/ch02_08_문자열_응용_공유_ipynb의_사본.ipynb
  submission/KHB2937/ch02_09_문자열_서식_qus0in_ipynb의_사본.ipynb
  submission/KHB2937/ch02_10_딕셔너리_응용_공유용_ipynb의_사본.ipynb
Labels: 필기, STAR

#144 2023.03.06 회고
  submission/hiid0726/ch02_03_복습.ipynb
  submission/hiid0726/ch02_09_문자열_서식_ym.ipynb
  submission/hiid0726/ch02_10_딕셔너리_응용_ym.ipynb
  submission/hiid0726/ch03_01_함수_ym.ipynb
Labels: 필기, STAR

#145 23.03.06 수업
  submission/CHOISEONGGU/Ch02_03_복습.ipynb
  submission/CHOISEONGGU/ch02_09_문자열_서식_ChoiSG.ipynb
  submission/CHOISEONGGU/ch02_10_딕셔너리_응용_ChoiSG.ipynb
  submission/CHOISEONGGU/ch03_01_함수_ChoiSG.ipynb
Labels: 필기, 4줄일기

#146 2023.03.06
  submission/zihvvan/ch02_07_리스트_응용_zihvvan.ipynb
  submission/zihvvan/ch02_09_문자열_서식.ipynb
  submission/zihvvan/ch02_10_딕셔너리_응용.ipynb
  submission/zihvvan/ch03_01_함수.ipynb
Labels: 필기, 4줄일기

#147 Day05 회고
  submission/Myun9hyun/02_function/app.py
Labels: 필기, STAR

#148 5일차 회고
  submission/jaiwon880/CH02_04_복습.ipynb
  submission/jaiwon880/ch02_03_복습2.ipynb
  submission/jaiwon880/ch03_02_클래스.ipynb
  submission/jaiwon880/ch03_03_예외처리.ipynb
Labels: 필기, STAR

#149 2023/03/06 수업
  submission/JoySoon/ch02_03_복습_KSW.ipynb
  submission/JoySoon/ch02_09_문자열_서식_KSW.ipynb
  submission/JoySoon/ch02_10_딕셔너리_응용_KSW.ipynb
  submission/JoySoon/ch03_01_함수_KSW.ipynb
Labels: 필기, 4줄일기

#150 회고
  submission/jinu/ch02_01_복습.ipynb
  submission/jinu/ch02_01_불과+비교+논리+연산자_qus0in.ipynb
Labels: 필기, 4줄일기

#151 2023_03_06_회고
  material/02_second_webapp/app.py
  material/02_second_webapp/requirements.txt
  submission/cc5547/2023_03_07_CH02_04_복습.ipynb
  submission/cc5547/2023_03_07_CH03_01_복습.ipynb
  submission/cc5547/2023_03_07_ch03_02_클래스.ipynb
  submission/cc5547/2023_03_07_ch03_03_예외처리.ipynb
Labels: 필기, 4줄일기

#152 23.03.06 수업 회고
  submission/JaejinLee1215/ch02_03_복습.ipynb
  submission/JaejinLee1215/ch02_04_복습.ipynb
  submission/JaejinLee1215/ch03_01_복습.ipynb
  submission/JaejinLee1215/ch03_01_함수_이재진.ipynb
  submission/JaejinLee1215/ch03_03_예외처리_이재진.ipynb
Labels: 필기, STAR

#153 23.03.06 회고
  submission/mastgm0817/00_practice_webapp/app.py
  submission/mastgm0817/00_practice_webapp/국비지원반.CSV
  submission/mastgm0817/02_second_webapp/app.py
  submission/mastgm0817/02_second_webapp/requirements.txt
  submission/mastgm0817/lecture/Ch02/ch02_07_리스트_응용.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_07_반복문.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_08_문자열_응용.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_09_문자열_서식.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_10_딕셔너리_응용.ipynb
  submission/mastgm0817/lecture/SelfStudy/리스트관련_복습.ipynb
Labels: 필기, 4줄일기

#154 2023.03.07(회고)
  submission/hiid0726/ch02_04.ipynb
  submission/hiid0726/ch03_01복습.ipynb
  submission/hiid0726/ch03_02_클래스_ym.ipynb
  submission/hiid0726/ch03_03_예외처리_ym.ipynb
  submission/hiid0726/ch04_01_모듈과_패키지_ym.ipynb
  submission/hiid0726/ch04_02_날짜와_시간_ym.ipynb
Labels: 필기, STAR

#155 0307
  submission/andy9806/0307.ipynb
Labels: 필기, STAR

#156 23.03.07 회고
  submission/mastgm0817/lecture/Ch01/ch01_02_변수+입력+출력.ipynb
  submission/mastgm0817/lecture/Ch01/ch01_03_MarkDown.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_01_불과+비교+논리+연산자.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_02_문자열.ipynb
  submission/mastgm0817/lecture/Ch02/ch02_03_리스트와_튜플.ipynb
  submission/mastgm0817/lecture/Ch03/CH03_01_복습.ipynb
  submission/mastgm0817/lecture/Ch03/ch03_02_클래스.ipynb
  submission/mastgm0817/lecture/Ch03/ch03_03_예외처리.ipynb
Labels: 필기, 4줄일기

#157 23.03.07 회고
  submission/CHOISEONGGU/Ch03_01_함수_복습.ipynb
  submission/CHOISEONGGU/ch03_02_클래스_ChoiSG.ipynb
  submission/CHOISEONGGU/ch03_03_예외처리_ChoiSG.ipynb
  submission/CHOISEONGGU/ch04_01_모듈과_패키지_ChoiSG.ipynb
  submission/CHOISEONGGU/ch04_02_날짜와_시간_ChoiSG.ipynb
Labels: 필기, 4줄일기

#158 2023.03.07
  submission/zihvvan/ch03_01_복습.ipynb
  submission/zihvvan/ch03_02_클래스.ipynb
  submission/zihvvan/ch03_03_예외처리.ipynb
  submission/zihvvan/ch04_01_모듈과_패키지.ipynb
  submission/zihvvan/ch04_02_날짜와_시간.ipynb
Labels: 필기, KPT

#159 Day 06 회고
  submission/Myun9hyun/ch03_02_클래스_공유용.ipynb
  submission/Myun9hyun/ch03_03_예외처리_공유용.ipynb
  submission/Myun9hyun/ch04_01_모듈과_패키지_공유용.ipynb
  submission/Myun9hyun/ch04_02_날짜와_시간_공유용.ipynb
Labels: 필기, 4줄일기

#161 03/07 회고
  submission/whataLin/ch03/ch03_02_클래스.ipynb
  submission/whataLin/ch03/ch03_03_예외처리.ipynb
  submission/whataLin/ch03/ch03_정리1_함수.ipynb
  submission/whataLin/ch04/ch04_01_모듈과_패키지.ipynb
  submission/whataLin/ch04/ch04_02_날짜와_시간.ipynb
Labels: 필기, STAR

#162 day6
  submission/jyeongvv/ch02_03_복습.ipynb
  submission/jyeongvv/ch02_04_복습.ipynb
  submission/jyeongvv/ch02_09_문자열.ipynb
  submission/jyeongvv/ch02_10_딕셔너리_응용.ipynb
  submission/jyeongvv/ch03_01_복습.ipynb
  submission/jyeongvv/ch03_01_함수.ipynb
  submission/jyeongvv/ch03_02_클래스.ipynb
  submission/jyeongvv/ch03_03_예외처리.ipynb
  submission/jyeongvv/ch04_01_모듈과_패키지.ipynb
  submission/jyeongvv/ch04_02_날짜와_시간.ipynb
Labels: 필기, 4줄일기

#163 03-07 회고
  submission/KHB2937/CH02_04_복습_ipynb의_사본.ipynb
  submission/KHB2937/ch03_01_함수_공유용_ipynb의_사본.ipynb
  submission/KHB2937/ch03_02_클래스_kwak99_ipynb의_사본.ipynb
  submission/KHB2937/ch03_03_예외처리_kwak99_ipynb의_사본.ipynb
  submission/KHB2937/ch04_02_날짜와_시간_kwak99_ipynb의_사본.ipynb
Labels: 필기, KPT

#164 회고
  submission/jinu/ch02_01_복습.ipynb
  submission/jinu/ch02_01_불과+비교+논리+연산자_qus0in.ipynb
Labels: 필기, 4줄일기

#165 pr용
  submission/tkd8973/리스트_복습_.ipynb
Labels: 필기, KPT

#166 3월 7일 6일차 회고
  submission/Yeaaaaaaah/ch03_02_클래스.ipynb
  submission/Yeaaaaaaah/ch03_03_예외처리.ipynb
  submission/Yeaaaaaaah/ch04_01_모듈과_패키지.ipynb
  submission/Yeaaaaaaah/ch04_02_날짜와_시간.ipynb
Labels: 필기, 4줄일기

#167 2023/03/07
  submission/JoySoon/ch03_02_클래스_KSW.ipynb
  submission/JoySoon/ch03_03_예외처리_KSW.ipynb
  submission/JoySoon/ch04_01_모듈과_패키지_KSw.ipynb
  submission/JoySoon/ch04_02_날짜와_시간_KSW.ipynb
Labels: 필기, KPT

#169 2023_03_07_회고
  material/02_second_webapp/app.py
  submission/cc5547/02_second_webapp/app.py
  submission/cc5547/02_second_webapp/requirements.txt
  submission/cc5547/2023_03_07_ch04_01_모듈과_패키지.ipynb
  submission/cc5547/2023_03_07_ch04_02_날짜와_시간.ipynb
  submission/cc5547/2023_03_08_ch03_02_복습.ipynb
Labels: 필기, 4줄일기

#170 2023.03.07 회고
  submission/suhdongjoon/ch02_09_문자열_서식_sdj.ipynb
  submission/suhdongjoon/ch02_10_문자열_응용_sdj.ipynb
  submission/suhdongjoon/ch03_01_함수_sdj.ipynb
  submission/suhdongjoon/ch03_02_클래스_sdj.ipynb
  submission/suhdongjoon/ch03_03_예외처리_sdj.ipynb
  submission/suhdongjoon/ch04_01_모듈과_패키지_sdj.ipynb
  submission/suhdongjoon/ch04_02_날짜와_시간_sdj.ipynb
Labels: 필기, KPT
